sudo: required
services: 
  - docker

before_install: 
  - docker build -t brandonjones085/puprate-test -f ./puprate/Dockerfile.dev ./puprate 

script: 
  - echo "RUNNING SCRIPT"

after_success: 
  - docker build -t brandonjones085/puprate-nginx ./nginx
  - docker build -t brandonjones085/puprate-angular ./puprate
  - docker build -t brandonjones085/puprate-express ./backend


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push brandonjones085/puprate-nginx 
  - docker push brandonjones085/puprate-angular
  - docker push brandonjones085/puprate-express
  


# deploy: 
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "puprate-docker"
#   env: "PuprateDocker-env"
#   bucket_name: elasticbeanstalk-us-west-1-243279705396
#   bucket_path: "docker-puprate"
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: 
#     secure: "$AWS_SECRET_KEY"
